# Generated by Django 3.1.8 on 2021-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210518_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_do_tasks',
            old_name='time',
            new_name='starts',
        ),
        migrations.AddField(
            model_name='to_do_tasks',
            name='ends',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
