# Generated by Django 3.1.8 on 2021-05-20 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210518_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_tasks',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 20)),
        ),
        migrations.AlterField(
            model_name='to_do_tasks',
            name='starts',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
