# Generated by Django 3.1.8 on 2021-05-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
