# Generated by Django 3.1.8 on 2021-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.DateField(),
        ),
    ]
